
[buildPlans.IosevkaTermCustom]
family = "Iosevka Term Custom"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.IosevkaTermCustom.variants]
  inherits = "ss08"

    [buildPlans.IosevkaTermCustom.variants.design]
    zero = "tall-slashed"
    a = "double-storey-serifless"
    g = "single-storey-top-cut"
    t = "narrow-bent-hook"
    lig-neq = "more-slanted"
    lig-equal-chain = "without-notch"

    [buildPlans.IosevkaTermCustom.variants.italic]
    zero = "tall-slashed"
    a = "single-storey-serifless"
    g = "single-storey-top-cut"

  [buildPlans.IosevkaTermCustom.ligations]
  inherits = "clike"

[buildPlans.IosevkaTermCustom.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaTermCustom.weights.Bold]
shape = 700
menu = 700
css = 700

[buildPlans.IosevkaTermCustom.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaTermCustom.slopes.Italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"

